version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails-skeleton-api
    container_name: rails-skeleton-api
    env_file: .env
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "${APP_PORT:-3000}:3000"
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:17-alpine
    container_name: rails-skeleton-api-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  bundle_cache:
